### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by abrahm** [aluanhaddad/aurelia-types-installer#2]
Aluan,

The current aurelia-types-installer npm package has CRLF EOLs in all the files. I'm guessing it was packaged on windows with `git config core.autocrlf=true`, which means that the `bin/ati` script as-packaged won't run on *NIX platforms because a carriage return ends up on the shebang line.

There is a fairly easy workaround, I just had to manually remove the carriage return from bin/ati after npm installed the package.

I suspect doing `git config core.autocrlf input` on windows might keep the newlines *NIX friendly for packaging on npm. (You can refresh an existing checkout by deleting .git/index followed by git reset... git status should then show what looks different without the autocrlf applied at checkout).

This isn't really a bug, but if you wanted to you could read this as an enhancement request to add a .gitattributes to maybe avoid this problem in the future.

Some similar discussion can be found at [npm issue 2097](https://github.com/npm/npm/issues/2097).

Have a nice day!

**Comment by aluanhaddad** [comment]
@abrahm, thank you for the bug report, it is much appreciated.

The CI builds run in Linux environments but they invoke the entry point directly using ts-node instead of hitting the `bin/ati` script.

Thank you for the detailed analysis and for explaining how to resolve the issue.

**Comment by aluanhaddad** [comment]
I ended up going the `.gitattributes` route, great tip by the way.

I drafted release [0.2.8](https://github.com/aluanhaddad/aurelia-types-installer/releases/tag/v0.2.8) to resolve this.
